server:
  port: 0

spring:
  application:
    name: user-service
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://db-mysql.co923mei4igr.us-east-1.rds.amazonaws.com:3306/test_db
    username: admin
    password: Aws92834001

greeting:
  message: Welcome to the Simple E-commerce
eureka:
  client:
    fetch-registry: true
    register-with-eureka: true
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}


token:
  expiration_time: 864000000
  secret: user_token


logging:
  level:
    com.example.userservice: debug
